// Code generated by "stringer -type=Code -linecomment"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeValidation-10000]
	_ = x[CodeTokenValidation-10001]
	_ = x[CodePassword-10002]
	_ = x[CodeTokenExpired-10003]
	_ = x[CodeAccessDenied-10004]
	_ = x[CodePlzLogin-10005]
	_ = x[CodeRecordNotFound-10100]
	_ = x[CodeNameDuplicate-10101]
	_ = x[CodeDatabaseOp-10102]
	_ = x[CodeRecordNotEnough-10103]
	_ = x[CodeNoUpdateRows-10104]
	_ = x[CodeSystemErr-10200]
}

const (
	_Code_name_0 = "参数校验错误Token 校验失败密码错误Token 过期没有权限请先登录"
	_Code_name_1 = "记录未找到名称重复数据库操作错误记录数量不足没有更新任何行"
	_Code_name_2 = "系统内部错误"
)

var (
	_Code_index_0 = [...]uint8{0, 18, 36, 48, 60, 72, 84}
	_Code_index_1 = [...]uint8{0, 15, 27, 48, 66, 87}
)

func (i Code) String() string {
	switch {
	case 10000 <= i && i <= 10005:
		i -= 10000
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case 10100 <= i && i <= 10104:
		i -= 10100
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	case i == 10200:
		return _Code_name_2
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
